2019-02-27 22:46:01,867 ERROR: Exception on /admin/department [POST] [in /home/holger/.local/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/labHandle/app/admin/routes.py", line 86, in add_department
    dep.from_dict(**json_obj)
  File "/home/holger/git/labHandle/app/base_model.py", line 183, in from_dict
    and query.filter_by(id=item["id"])
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1690, in filter_by
    return self.filter(sql.and_(*clauses))
  File "<string>", line 2, in filter
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 198, in generate
    self = args[0]._clone()
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/dynamic.py", line 289, in _clone
    orm_util.instance_str(instance), self.attr.key))
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Department at 0x7f4921c6b4a8> is not bound to a Session, and no contextual session is established; lazy load operation of attribute 'users' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
2019-02-27 22:49:01,465 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 22:49:06,947 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 22:49:13,939 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 22:49:22,249 ERROR: Exception on /admin/department [POST] [in /home/holger/.local/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/labHandle/app/admin/routes.py", line 86, in add_department
    dep.from_dict(**json_obj)
  File "/home/holger/git/labHandle/app/base_model.py", line 183, in from_dict
    and query.filter_by(id=item["id"])
AttributeError: 'InstrumentedList' object has no attribute 'filter_by'
2019-02-27 22:51:05,474 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 22:51:13,112 ERROR: Exception on /admin/department [POST] [in /home/holger/.local/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/labHandle/app/admin/routes.py", line 86, in add_department
    dep.from_dict(**json_obj)
  File "/home/holger/git/labHandle/app/base_model.py", line 183, in from_dict
    and query.filter_by(id=item["id"])
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1690, in filter_by
    return self.filter(sql.and_(*clauses))
  File "<string>", line 2, in filter
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 198, in generate
    self = args[0]._clone()
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/dynamic.py", line 289, in _clone
    orm_util.instance_str(instance), self.attr.key))
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Department at 0x7f5be6940eb8> is not bound to a Session, and no contextual session is established; lazy load operation of attribute 'users' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
2019-02-27 23:00:58,627 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 23:01:07,418 ERROR: Exception on /admin/department [POST] [in /home/holger/.local/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/labHandle/app/admin/routes.py", line 86, in add_department
    dep.from_dict(**json_obj)
  File "/home/holger/git/labHandle/app/base_model.py", line 210, in from_dict
    for item in query.filter(not_(cls.id.in_(valid_ids))).all():
NameError: name 'not_' is not defined
2019-02-27 23:05:47,787 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 23:05:54,264 ERROR: Exception on /admin/department [POST] [in /home/holger/.local/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/labHandle/app/admin/routes.py", line 86, in add_department
    dep.from_dict(**json_obj)
  File "/home/holger/git/labHandle/app/base_model.py", line 210, in from_dict
    for item in query.filter(~(cls.id.in_(valid_ids))).all():
  File "<string>", line 2, in filter
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 198, in generate
    self = args[0]._clone()
  File "/home/holger/.local/lib/python3.5/site-packages/sqlalchemy/orm/dynamic.py", line 289, in _clone
    orm_util.instance_str(instance), self.attr.key))
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Department at 0x7f4fa1b540b8> is not bound to a Session, and no contextual session is established; lazy load operation of attribute 'users' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
2019-02-27 23:06:48,654 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 23:07:42,253 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
2019-02-27 23:13:49,629 INFO: Length dep. server startup [in /home/holger/git/labHandle/app/__init__.py:76]
