2019-01-09 16:19:01,394 ERROR: Exception on /search [GET] [in c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\main\routes.py", line 23, in search
    if args:
NameError: name 'args' is not defined
2019-01-09 16:19:30,082 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:19:33,218 ERROR: Exception on /search [GET] [in c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-01-09 16:20:15,775 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:20:37,521 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:21:59,109 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:22:53,865 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:22:56,642 ERROR: Exception on /search [GET] [in c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\main\routes.py", line 23, in search
    print(res.realname)
AttributeError: 'NoneType' object has no attribute 'realname'
2019-01-09 16:23:21,446 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:23:56,312 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:24:19,511 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:24:46,687 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:25:19,978 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:27:08,491 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:31:09,809 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:38:04,211 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:38:06,178 ERROR: Exception on /search [GET] [in c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\main\routes.py", line 21, in search
    print(file.bytes())
AttributeError: 'str' object has no attribute 'bytes'
2019-01-09 16:38:21,014 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:38:22,012 ERROR: Exception on /search [GET] [in c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\holger\documents\git\gitlab_internal\proto_qry\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\main\routes.py", line 21, in search
    print(bytes(file))
TypeError: string argument without an encoding
2019-01-09 16:38:36,599 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:39:02,448 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:39:35,598 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-09 16:40:39,170 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\gitlab_internal\proto_qry\app\__init__.py:48]
2019-01-10 09:03:12,047 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\proto_qry\app\__init__.py:48]
